execute pathogen#infect()

let fortran_free_source=1
set number
set hlsearch
syntax on

set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P

" Appearance
set background=dark
let base16colorspace=256
colorscheme base16-atelierforest

nnoremap <Leader>s :%s/\<<C-r><C-w>\>//g<Left><Left>
nnoremap <F2> :GundoToggle<CR>
nnoremap <F3> :TagbarToggle<CR>
